In [ ]:
    Q1. A company conducted a survey of its employees and found that 70% of the employees use the
    company's health insurance plan, while 40% of the employees who use the plan are smokers. What is the
    probability that an employee is a smoker given that he/she uses the health insurance plan?

In [ ]:
Ans : To find the probability that an employee is a smoker given that he/she uses the health insurance plan, we can use conditional probability.

    Let:
        A be the event that an employee uses the health insurance plan.
        S be the event that an employee is a smoker.
        
        P(A), the probability that an employee uses the health insurance plan, which is 70% or 0.70.
        P(S∣A), the conditional probability that an employee is a smoker given that they use the health 
        insurance plan, which is 40% or 0.40.
        
        We want to find 
            P(S∣A), the probability that an employee is a smoker given that they use the health insurance plan.

            We can use the formula for conditional probability:
                P(S∣A) = P(S and A) / P(A)     
                P(S and A)=P(A)⋅P(S∣A)
                    Substituting the values:
                    P(S and A)=0.70⋅0.40=0.28
                    
                                P(S∣A) = 0.28 / 0.70 = 0.4
            So, the probability that an employee is a smoker given that he/she uses the health insurance plan is approximately 0.4 or 40%.

In [ ]:
Q2. What is the difference between Bernoulli Naive Bayes and Multinomial Naive Bayes?

In [ ]:
Ans :  Bernoulli Naive Bayes and Multinomial Naive Bayes are two variants of the Naive Bayes classifier that are used for different 
       types of data and have distinct characteristics:
        
        1. Bernoulli Naive Bayes:

            a. Data Type: Bernoulli Naive Bayes is primarily used for binary or Boolean data, where each feature is either present (1) 
               or absent (0). It's suitable for data where you want to model the presence or absence of specific characteristics or attributes.
            b. Example Use Cases: Text classification problems where the presence or absence of specific words in documents is important 
               (e.g., spam detection, sentiment analysis).
            c. Probability Calculation: It models the probability of each feature (word) being either present or absent in a document
               for each class. It assumes that the features are conditionally independent given the class, similar to other Naive Bayes variants.
            d. Use of the Bernoulli Distribution: It often employs the Bernoulli distribution to calculate probabilities for binary features.
        
        
        2. Multinomial Naive Bayes:

            a. Data Type: Multinomial Naive Bayes is used for data that represents counts or frequencies of events. It's suitable for 
               problems where you're dealing with discrete data, such as text data where you have word counts or term frequencies.
            b. Example Use Cases: Document classification, text categorization, and any task where you're working with count-based features.
            c. Probability Calculation: It models the probability distribution of the counts of each feature (word) for each class. 
               It assumes that the features follow a multinomial distribution and are conditionally independent given the class.
            d. Use of the Multinomial Distribution: It often employs the multinomial distribution to calculate probabilities for
               count-based features.
        
        the main difference between Bernoulli Naive Bayes and Multinomial Naive Bayes lies in the type of data they are suited for. 
        Bernoulli Naive Bayes is for binary data (presence/absence), while Multinomial Naive Bayes is for count-based data. 

In [ ]:
Q3. How does Bernoulli Naive Bayes handle missing values?

In [ ]:
Ans : Bernoulli Naive Bayes, like other Naive Bayes variants, generally doesn't handle missing values in a straightforward manner.
      It assumes that each feature is either present (1) or absent (0), so missing values are typically treated as a specific 
      category or state of the feature. Here's how missing values are typically handled:
        
        1. reat Missing Values as a Category:
                In Bernoulli Naive Bayes, missing values are often treated as a separate category or state of the feature.
                This means that for each feature with missing values, the classifier considers the possibility that the feature 
                is neither present (0) nor absent (1), but rather "missing" (represented as, for example, -1).
        2. Imputation:
                Prior to applying Bernoulli Naive Bayes, you may choose to impute missing values using a specific strategy.
                Common imputation methods include replacing missing values with the most common category (mode imputation) or 
                using more advanced techniques like regression imputation or k-nearest neighbors imputation.
                
        3. Feature Engineering:
                Another approach is to engineer additional binary features that explicitly indicate the presence or absence of 
                missing values for each original feature. This can help the classifier account for the information about which 
                values were missing.

In [ ]:
Q4. Can Gaussian Naive Bayes be used for multi-class classification?

In [ ]:
Ans : Yes, Gaussian Naive Bayes can be used for multi-class classification. Gaussian Naive Bayes is a variant of the Naive Bayes 
      algorithm that is particularly suited for data where features follow a Gaussian (normal) distribution. While it's often 
      associated with binary classification problems, it can also be adapted for multi-class classification tasks.

In [ ]:
Q5. Assignment:

In [2]:
import numpy as np
import pandas as pd

In [26]:
data = pd.read_csv("spambase.data", header=None)


In [27]:
data

0     1     2    3     4     5     6     7     8     9   ...     48  \
0     0.00  0.64  0.64  0.0  0.32  0.00  0.00  0.00  0.00  0.00  ...  0.000   
1     0.21  0.28  0.50  0.0  0.14  0.28  0.21  0.07  0.00  0.94  ...  0.000   
2     0.06  0.00  0.71  0.0  1.23  0.19  0.19  0.12  0.64  0.25  ...  0.010   
3     0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.000   
4     0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.000   
...    ...   ...   ...  ...   ...   ...   ...   ...   ...   ...  ...    ...   
4596  0.31  0.00  0.62  0.0  0.00  0.31  0.00  0.00  0.00  0.00  ...  0.000   
4597  0.00  0.00  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.000   
4598  0.30  0.00  0.30  0.0  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.102   
4599  0.96  0.00  0.00  0.0  0.32  0.00  0.00  0.00  0.00  0.00  ...  0.000   
4600  0.00  0.00  0.65  0.0  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.000   

         49   50     51     52     53     54   55    56  57  
0     0.000  0.0  0.778  0.000  0.000  3.756   61   278   1  
1     0.132  0.0  0.372  0.180  0.048  5.114  101  1028   1  
2     0.143  0.0  0.276  0.184  0.010  9.821  485  2259   1  
3     0.137  0.0  0.137  0.000  0.000  3.537   40   191   1  
4     0.135  0.0  0.135  0.000  0.000  3.537   40   191   1  
...     ...  ...    ...    ...    ...    ...  ...   ...  ..  
4596  0.232  0.0  0.000  0.000  0.000  1.142    3    88   0  
4597  0.000  0.0  0.353  0.000  0.000  1.555    4    14   0  
4598  0.718  0.0  0.000  0.000  0.000  1.404    6   118   0  
4599  0.057  0.0  0.000  0.000  0.000  1.147    5    78   0  
4600  0.000  0.0  0.125  0.000  0.000  1.250    5    40   0  

[4601 rows x 58 columns]

In [38]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [39]:
X

0     1     2    3     4     5     6     7     8     9   ...   47  \
0     0.00  0.64  0.64  0.0  0.32  0.00  0.00  0.00  0.00  0.00  ...  0.0   
1     0.21  0.28  0.50  0.0  0.14  0.28  0.21  0.07  0.00  0.94  ...  0.0   
2     0.06  0.00  0.71  0.0  1.23  0.19  0.19  0.12  0.64  0.25  ...  0.0   
3     0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.0   
4     0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.0   
...    ...   ...   ...  ...   ...   ...   ...   ...   ...   ...  ...  ...   
4596  0.31  0.00  0.62  0.0  0.00  0.31  0.00  0.00  0.00  0.00  ...  0.0   
4597  0.00  0.00  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.0   
4598  0.30  0.00  0.30  0.0  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.0   
4599  0.96  0.00  0.00  0.0  0.32  0.00  0.00  0.00  0.00  0.00  ...  0.0   
4600  0.00  0.00  0.65  0.0  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.0   

         48     49   50     51     52     53     54   55    56  
0     0.000  0.000  0.0  0.778  0.000  0.000  3.756   61   278  
1     0.000  0.132  0.0  0.372  0.180  0.048  5.114  101  1028  
2     0.010  0.143  0.0  0.276  0.184  0.010  9.821  485  2259  
3     0.000  0.137  0.0  0.137  0.000  0.000  3.537   40   191  
4     0.000  0.135  0.0  0.135  0.000  0.000  3.537   40   191  
...     ...    ...  ...    ...    ...    ...    ...  ...   ...  
4596  0.000  0.232  0.0  0.000  0.000  0.000  1.142    3    88  
4597  0.000  0.000  0.0  0.353  0.000  0.000  1.555    4    14  
4598  0.102  0.718  0.0  0.000  0.000  0.000  1.404    6   118  
4599  0.000  0.057  0.0  0.000  0.000  0.000  1.147    5    78  
4600  0.000  0.000  0.0  0.125  0.000  0.000  1.250    5    40  

[4601 rows x 57 columns]

In [40]:
y

0       1
1       1
2       1
3       1
4       1
       ..
4596    0
4597    0
4598    0
4599    0
4600    0
Name: 57, Length: 4601, dtype: int64

In [28]:
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB
from sklearn.model_selection import cross_val_score

In [41]:
bernoulli = BernoulliNB()
multinomial = MultinomialNB()
gaussian = GaussianNB()

In [42]:
from sklearn.model_selection import train_test_split

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=42)

In [46]:
X_train.shape, X_test.shape

((3450, 57), (1151, 57))

In [47]:
bernoulli.fit(X_train,y_train)

BernoulliNB()

In [48]:
y_pred_bernoulli = bernoulli.predict(X_test)

In [49]:
y_pred_bernoulli

array([0, 0, 0, ..., 1, 0, 0])

In [50]:
from sklearn.metrics import accuracy_score,classification_report

In [51]:
print(accuracy_score(y_pred_bernoulli,y_test))

0.8827106863596872


In [52]:
print(classification_report(y_pred_bernoulli,y_test))

              precision    recall  f1-score   support

           0       0.94      0.87      0.90       727
           1       0.80      0.90      0.85       424

    accuracy                           0.88      1151
   macro avg       0.87      0.89      0.88      1151
weighted avg       0.89      0.88      0.88      1151



In [53]:
multinomial.fit(X_train,y_train)

MultinomialNB()

In [54]:
y_pred_multinomial = multinomial.predict(X_test)

In [55]:
y_pred_multinomial

array([1, 0, 0, ..., 0, 0, 0])

In [57]:
print(accuracy_score(y_pred_multinomial,y_test))

0.7914856646394439


In [58]:
print(classification_report(y_pred_multinomial,y_test))

              precision    recall  f1-score   support

           0       0.85      0.81      0.83       714
           1       0.71      0.77      0.74       437

    accuracy                           0.79      1151
   macro avg       0.78      0.79      0.78      1151
weighted avg       0.80      0.79      0.79      1151



In [59]:
gaussian.fit(X_train,y_train)

GaussianNB()

In [60]:
y_pred_gaussian = gaussian.predict(X_test)

In [61]:
y_pred_gaussian

array([1, 0, 0, ..., 1, 0, 0])

In [62]:
print(accuracy_score(y_pred_gaussian,y_test))

0.8271068635968722


In [63]:
print(classification_report(y_pred_gaussian,y_test))

              precision    recall  f1-score   support

           0       0.74      0.95      0.83       527
           1       0.95      0.72      0.82       624

    accuracy                           0.83      1151
   macro avg       0.84      0.84      0.83      1151
weighted avg       0.85      0.83      0.83      1151



In [ ]:
BernoulliNB(): You achieved an accuracy of 0.8827 with this variant. Bernoulli Naive Bayes is typically used for binary or 
binarized data, such as text classification tasks where you represent each term as present (1) or absent (0). It performed 
well in this specific task.

Limitations of Naive Bayes:

        1. Assumption of Independence: Naive Bayes assumes that features are independent, which may not hold true in many 
           real-world datasets. This can lead to suboptimal results when features are correlated.

        2. Sensitivity to Feature Distribution: Each variant of Naive Bayes makes specific assumptions about the distribution 
           of features. If these assumptions are violated, the algorithm may perform poorly.

        3. Limited Expressiveness: Naive Bayes is a simple algorithm and may not capture complex relationships in the data as well 
           as more sophisticated algorithms like Random Forests or Neural Networks.
            
            
    Conclusion:

        In your case, Bernoulli Naive Bayes performed the best, but it's essential to choose the variant that aligns with the nature of your data.

    Future work could involve:

            Exploring other classification algorithms to see if they outperform Naive Bayes on your dataset.
            Feature engineering to create more informative features.
            Tuning hyperparameters for Naive Bayes or other models to improve performance.
            Assessing model robustness and handling imbalanced datasets if applicable.